### ISSUE TITLE
New pocketbase authentication endpoint changed but not reflected on this package

### ISSUE THREAD

**Issue by OniiCoder** [pocketbase/dart-sdk#15]
The Authentication endpoint on this currently is `/api/users` but the new Pocketbase version update has it as `/api/collections/users`. 

Due to this; there is a `Not found` response when authentication is initiated.

**Comment by ganigeorgiev** [comment]
I guess you are using PocketBase v0.8.0-rc.

If that's the case then you have to use the pre-release of the SDK too, aka.

```
dart pub add pocketbase:^0.5.0-rc1

# or with Flutter:
flutter pub add pocketbase:^0.5.0-rc1
```

You can find a SDK changelog in the `rc` branch - https://github.com/pocketbase/dart-sdk/blob/rc/CHANGELOG.md

Detailed v0.8.0 changelog with migration guide from v0.7.0  and all the breaking changes could be found in https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1.

Stable v0.8.0 will be available in the next 1-2 weeks.

**Comment by OniiCoder** [comment]
Thank you!
