### ISSUE TITLE
The named parameter 'expand' isn't defined.

### ISSUE THREAD

**Issue by uptechsolutionsghana** [pocketbase/dart-sdk#17]
How do i get relations from getFullList?

**Comment by ganigeorgiev** [comment]
What version of PocketBase and Dart SDK you are using?

For PocketBase v0.7.x and PocketBase Dart SDK <= 0.4.0, there is no `expand` named parameter you have to set it as part of the query map, aka:

```dart
client.records.getFullList("example", query : { "expand": "someRelField" })
```
