### ISSUE TITLE
I cant create new collections and edit fields

### ISSUE THREAD

**Issue by Litioblue** [pocketbase/dart-sdk#19]
Hello everyone.
First I want to thank everyone who has done this work. is awesome!.

Now the problem is that after migrating to version 8 I can't create new collections and I can't edit the fields of the ones I already had created.

I receive the message: 
![image](https://user-images.githubusercontent.com/111813067/204833384-ba463148-f003-4634-8d4f-6f6942aac516.png)
![image](https://user-images.githubusercontent.com/111813067/204833568-4af028c2-acc6-4b5a-8dff-e4f82f42f736.png)

thanks so much.

**Comment by ganigeorgiev** [comment]
From the screenshot and visible sidebar collections it doesn't seems that you've migrated fully to v0.8.0.

Did you follow the migration guide from https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#migrate-from-v07x?

Note that you have to execute an `upgrade` command to update your data structure (make sure to have a copy of your `pb_data` before that in case something goes wrong).

**Comment by ganigeorgiev** [comment]
I'll close the issue because this is not related to the Dart SDK, but feel free to comment or [open a discussion in the main repo](https://github.com/pocketbase/pocketbase/discussions/new) if you are still having difficulties with the upgrade.
