### ISSUE TITLE
Caching API requests 

### ISSUE THREAD

**Issue by jeffrey0606** [pocketbase/dart-sdk#26]
Please can we have a Caching option for requests using the package **Dio**?

**Comment by ganigeorgiev** [comment]
We use [`dart-lang/http`](https://github.com/dart-lang/http) as a http client.

Client-side data caching is up to the developers and at least for now there are no plans to integrate it inside the SDK.

Server-side caching controls could be added in the near future but [other tasks](https://github.com/orgs/pocketbase/projects/2) are with higher priority at the moment.
