### ISSUE TITLE
Dart suggestion code should not contain quotes

### ISSUE THREAD

**Issue by jarrodcolburn** [pocketbase/dart-sdk#34]
'expand' in dart is quoted. But it's a parameter (not a JSON key)

please see 
[Screen recording 2023-04-14 19.49.17.webm](https://user-images.githubusercontent.com/16673615/232174986-9b16bf1b-a971-43aa-aae7-9cdabad83b93.webm)

**Comment by ganigeorgiev** [comment]
Thanks, I'll update the example docs in the next release since they are part of the ui in https://github.com/pocketbase/pocketbase repo.
