### ISSUE TITLE
how to yield from subscription function

### ISSUE THREAD

**Issue by tonyhart7** [pocketbase/dart-sdk#40]
![image](https://user-images.githubusercontent.com/42036827/234838209-6082e28a-4dee-4447-b7a9-d175fdc17d13.png)

I am using riverpod with StreamProvider and want to use yield when new record created but I cant do that because RecordSubscriptionEven output Void at the end

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand your use case but I don't think you can `yield` to the parent context from within the subscribe callback even if the function was `async*`.

You can try to create your own stream and push data to it via the `subscribe` callback.
Then inside the riverpod function you can use the `await for` (_not `.listen(...)`_) construct with your stream and yield within its block.

**Comment by tonyhart7** [comment]
> I'm not sure that I understand your use case but I don't think you can `yield` to the parent context from within the subscribe callback even if the function was `async*`.
> 
> You can try to create your own stream and push data to it via the `subscribe` callback. Then inside the riverpod function you can use the `await for` (_not `.listen(...)`_) construct with your stream and yield within its block.

![image](https://user-images.githubusercontent.com/42036827/234843584-a01b6196-ce1f-4ed8-928a-d9326ce4b1f2.png)

Okay its works, but how to query old data tho ?? 

like I want to aquire existing data if there are some but as long as new data get inserted. it gets automatically added

**Comment by ganigeorgiev** [comment]
> Okay its works, but how to query old data tho ??

PocketBase realtime events reacts only on changes (aka. create/update/delete of a record).

If you want to fetch the already inserted data you'll have to query it manually with the regular `getList()`/`getFullList()` methods.

**Comment by ganigeorgiev** [comment]
_By the way, you can also check the [`StateProvider`](https://pub.dev/documentation/riverpod/latest/riverpod/StateProvider-class.html) which might be better for your use case since you'll not need the extra stream._

In any case, I'll close the issue for now but feel free to comment if you stumble on something else.
