### ISSUE TITLE
Upgrade http to 1.0.0

### ISSUE THREAD

**Issue by jkoenig134** [pocketbase/dart-sdk#42]
As http version 1.0.0 is released I want to upgrade it in my project. The dependency of pocketbase sadly blocks this.
This could be done as a part of https://github.com/pocketbase/dart-sdk/pull/41.

**Comment by ganigeorgiev** [comment]
Yes, I'll consider updating the package soon (_currently the JS app hooks and Go internal refactoring is with higher priority_).

As a temporary workaround, you can try to overwrite the dependency with [`dependency_overrides`](https://dart.dev/tools/pub/dependencies#dependency-overrides) in your pubspec.yaml.

**Comment by jkoenig134** [comment]
@ganigeorgiev thanks for the fast response! It's not that urgent - I just wanted to mention it that it not gets forgotten!

**Comment by ganigeorgiev** [comment]
The http dependency was updated in v0.12.0.
