### ISSUE TITLE
Need info 

### ISSUE THREAD

**Issue by Rutik7066** [pocketbase/dart-sdk#44]
I am new to pb i just want to know that. Does pb dart sdk save auth data in browser on flutter web or should i have to save using other db like hive flutter

**Comment by ganigeorgiev** [comment]
Currently the Dart SDK doesn't have persistence and you have to implement your own [AuthStore](https://github.com/pocketbase/dart-sdk#authstore).

For an example for a custom auth store you can also check https://github.com/pocketbase/pocketbase/discussions/1887#discussioncomment-5057297.
