### ISSUE TITLE
Discord OAuth Issue

### ISSUE THREAD

**Issue by breezko** [pocketbase/dart-sdk#47]
I am trying to set up oauth with discord. However the code seems to be stuck. 
The last printed message to the console is `go` and the OAuth Flow looks never started and I dont get any exception or message.

```
import 'package:url_launcher/url_launcher.dart';
import 'package:pocketbase/pocketbase.dart';
....
print("go");
final pb = PocketBase('someurl.fly.dev');
        final authData2 =
            await pb.collection('users').authWithOAuth2('discord', (url) async {
              print(url);
          launchUrl(url);
        });
```
My Discord OAuth config:
![image](https://github.com/pocketbase/dart-sdk/assets/10911394/2c4b976c-1f67-48d0-a0ae-1b719d252d73)

My Pocketbase config:
![image](https://github.com/pocketbase/dart-sdk/assets/10911394/343a5960-051d-4347-96df-8008424abaf1)

**Comment by ganigeorgiev** [comment]
What platform do you target?

If it is Flutter Web, the realtime events are not supported there (_the "all-in-one" `authWithOAuth2()` call relies on a realtime subscription_) and you have to provide a custom http client (see https://github.com/pocketbase/dart-sdk#limitations).

**Comment by ganigeorgiev** [comment]
_Side-note: If you use Fly, also keep in mind that the last time I checked their free service had 60s limit for how long a connection can remain open, which is not an issue with the regular realtime subscriptions as there is autoreconnect, but with the "all-in-one" OAuth2 call that means that the OAuth2 sign process must happen under 60s, otherwise you'll get an error for "missing/invalid client id" or similar._

**Comment by ganigeorgiev** [comment]
I've just tested it locally with the Dart cli and I'm not able to reproduce it (_PocketBase Dart SDK v0.14.1 and PocketBase executable v0.17.7_).

```dart
// example.dart
import "dart:io";

import "package:pocketbase/pocketbase.dart";

void main() {
  final pb = PocketBase("http://127.0.0.1:8090");

  pb.collection("users").authWithOAuth2("discord", (url) async {
    // replace with "explorer" for windows or "open" for mac
    Process.run("xdg-open", [url.toString()]);
  }).then((result) {
    print("Result: $result");
  }).catchError((dynamic err) {
    print("Error: $err");
  });
}
```
Run with `dart run  example.dart`.

The above is running a shell comamnd to fire a browser window from the terminal but it should be the same with `url_launcher` or any other package (_the goal is to open the signin url from the callback a browser window_).

I suspect in your case you are testing in Flutter web, where as mentioned earlier, streamed responses are not supported out of the box and you have to provide your own http client as shown in https://github.com/pocketbase/dart-sdk#limitations.

If that's not the case, please provide more details on what platform your code is running and the versions of the PocketBase executable and SDK, and I'll investigate it further.

**Comment by breezko** [comment]
Thanks for the hint. Indeed I am using flutter. This issue was resolved by `httpClientFactory: kIsWeb ? () => FetchClient(mode: RequestMode.cors) : null,`

**Comment by ganigeorgiev** [comment]
_See the note in https://github.com/pocketbase/dart-sdk/issues/47#issuecomment-1696448024._

**Comment by breezko** [comment]
The issue was resolved. redirect_uri in the provider was incorrect.

**Comment by breezko** [comment]
Works for Flutter WEB:
```

final pb = PocketBase(
                'https://url.fly.dev',
                httpClientFactory: () => FetchClient(mode: RequestMode.cors),
              );
              final authData = await pb
                  .collection('users')
                  .authWithOAuth2('discord', (url) async {
                await launchUrl(url);
              });

              print(pb.authStore.isValid);
              print(pb.authStore.token);
              print(pb.authStore.model.id);
              ```
