### ISSUE TITLE
Username/Password authentication from Flutter Web

### ISSUE THREAD

**Issue by agreensh** [pocketbase/dart-sdk#49]
pocketbase 0.18.5 (linux arm64)
Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB) 

Trying to login with username/password now produces this exception:
"Expected a value of type 'Iterator', but got one of type 'DomIterator'"

pocketbase version and Flutter version both changed the same day. Was working before the updates (and still works from Android/iOS/Macos).
Any thoughts?

**Comment by ganigeorgiev** [comment]
I've tested it with both `shared_preferences` and the `fetch_client` and I'm not able to reproduce the error.

If you have a wrapping `try/catch` it is possible that the thrown error is from something else and not the auth request.

If you are still not able to identify the culprit, please create a **minimal** reproducible repo.

**Comment by agreensh** [comment]
dfdfdfdf

**Comment by ganigeorgiev** [comment]
Yes, I'm not able to reproduce it.

It could be also something browser specific, I'm not sure (I'm testing with Chrome 115).

**Comment by agreensh** [comment]
https://github.com/agreensh/pbauthemailpasswd

**Comment by agreensh** [comment]
you're correct.
with my site deployed to a server, it fails on Chrome but works on Safari, so I guess it's the Chrome version?

**Comment by ganigeorgiev** [comment]
Hm, indeed I've updated Chrome to 117 and it now fails, but I'm not sure why.

I'll try to create sometime later today a minimal reproducible example with just the `fetch_client` to narrow it down.

**Comment by ganigeorgiev** [comment]
I've added some more details in the issue that you've created in the `fetch_client` repo - https://github.com/Zekfad/fetch_client/issues/9.
