### ISSUE TITLE
Weird create function with body and files in Dart SDK

### ISSUE THREAD

**Issue by RonByRonn** [pocketbase/dart-sdk#53]
I am trying to create record with data and files (like example in [https://pocketbase.io/docs/files-handling/](https://pocketbase.io/docs/files-handling/))

here is my code:

```dart
final files = await Future.wait(
  images.map(
    (XFile image) => MultipartFile.fromPath(
      'images',
      image.path,
      filename: 'abc.jpg',
    ),
  ),
);

final body = <String, dynamic>{
  "text": "123",
};

final record = await pb.collection('collection').create(
  files: files,
  body: body,
);
```

but when I run above code, only `files` are successfully uploaded to DB and no `body` data is reflected in DB.
if I comment out `files` like this:

```dart
final record = await pb.collection('collection').create(
  // files: files,
  body: body,
);
```

then `body` is successfully uploaded to DB.

why is this happening and how can I solve this?
I can't find any difference between my code and example in [https://pocketbase.io/docs/files-handling/](https://pocketbase.io/docs/files-handling/)

thank you

**Comment by ganigeorgiev** [comment]
It works correctly for me and I'm not able to reproduce it locally with PocketBase v0.22.4 and PocketBase Dart SDK v0.18.1.


```dart
pb.collection("example").create(
  files: [
    http.MultipartFile.fromString(
      'file', // the name of the file field
      'example content...',
      filename: 'example_document.txt',
    ),
  ],
  body: {
    "title": "test",
  },
);
```

Note that PocketBase Dart SDK v0.18+ is compatible only with PocketBase 0.21+ (see the [CHANGELOG](https://pub.dev/packages/pocketbase/changelog)).

If you are still not able to resolve it, feel free to provide more details about your testing environment and/or create a **minimal** reproducible repo and I'll try to investigate it further.

**Comment by mttschltz** [comment]
> Note that PocketBase Dart SDK v0.18+ is compatible only with PocketBase v0.21+ (see the [CHANGELOG](https://pub.dev/packages/pocketbase/changelog)).

I had a similar problem. Upgrading the backend fixed it 👍 

I setup my Dart project a few weeks after my backend project, which is probably why I didn't check the changelog or consider the versions might be incompatible.
