### ISSUE TITLE
Riverpod PocketBase Problem or Misunderstanding

### ISSUE THREAD

**Issue by FantaMagier** [pocketbase/dart-sdk#56]
Hello everyone, 

thanks for the cool project and the SDK. As for the question of how to properly call your PocketBase instance and use other parts of the code, I thought a Riverpod provider would be a good solution. (See code below)

However, when logging in and logging out, I noticed that the state does not delete the user despite a .watch of the Riverpod. Is this a bug or what is the best use case for the PocketBase instance and the StateMangement for the current user? 

```dart
class PocketBaseNotifer extends StateNotifier<PocketBase?> {
  PocketBaseNotifer() : super(null) {
    loadPBStore().then((pb) => setPB(pb));
  }

  Future<PocketBase> loadPBStore() async {
    final prefs = await SharedPreferences.getInstance();

    final store = AsyncAuthStore(
      save: (String data) async {
        prefs.setString('pb_auth', data);
      },
      initial: prefs.getString('pb_auth'),
    );

    return PocketBase('POCKETBASEURL', authStore: store);
  }

  void setPB(PocketBase? pb) {
    state = pb;
  }

  void clearUser() {
    state?.authStore.clear();
  }
}

final pocketbaseProvider = StateNotifierProvider<PocketBaseNotifer, PocketBase?>(
  (ref) => PocketBaseNotifer(),
);

```

Flutter (Channel stable, 3.22.0)
pocketbase: ^0.18.1

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand the provided code sample, nor the described issue but I don't think it is PocketBase related.

There are automated tests that verify the correct behavior of both the client instance and the `AsyncAuthStore` and from what I can see it should correctly.

Note that if you don't set an explicit `clear` AsyncAuthStore constructor argument the current implement will call the save method with an empty string. For more details about the store helper you can check its [class pub.dev documentation](https://pub.dev/documentation/pocketbase/latest/pocketbase/AsyncAuthStore-class.html).

If you are still not able to resolve your issue, please elaborate a little more and provide clear reproducible steps (or **minimal** reproducible repo) and I'll try to have a more detailed look at it.
