### ISSUE TITLE
authWithOAuth2() lacks some parameters that authWithOAuth2Code() have

### ISSUE THREAD

**Issue by kaboc** [pocketbase/dart-sdk#62]
I'm thinking of adding the app info (platform and version) to the request header, but `authWithOAuth2()` does not have the `headers` parameter. I'm not sure if there is any reason for that, but if it is not impossible, it'd be great if it would be added, together with `body` and `query` that are also missing.

**Comment by ganigeorgiev** [comment]
I've added the extra arguments in [v0.19.0-rc3](https://pub.dev/packages/pocketbase/versions/0.19.0-rc3).

**Comment by kaboc** [comment]
Wow, so quick! Thank you as always.
