### ISSUE TITLE
`record.get<T>()` cannot get null value

### ISSUE THREAD

**Issue by azliR** [pocketbase/dart-sdk#63]
Hi, thank you for a great package and tools. I have a problem since i upgraded to version 0.19.0-rc3. So in 0.18.x we can specify it like this:
```dart
final userRecord = record.expand['user']?.first;
```
but after I upgraded to version 0.19.0-rc3, `record.expand` is deprecated and replaced by `get<T>`, but there is a problem, when the value is null, it throws an error, which have different behavior with the last version. Here is what i want to achieve and the error that i get:
```dart
final userRecord = record.get<RecordModel?>('expand.user');
```
output:
```
[log] StateError (Bad state: Invalid or unknown type value)
[log] #0      extract
caster.dart:53
#1      RecordModel.get
record_model.dart:99
#2      new Announcement.fromRecord
announcement.dart:44
#3      getPosts.<anonymous closure>
class_detail_provider.dart:45
#4      new ResponseList.fromResultList.<anonymous closure>
responses.dart:33
#4      new ResponseList.fromResultList.<anonymous closure>
responses.dart:33
#5      IterableMapIndexed.mapIndexed
iterable.dart:768
#6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:560:14)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#9      new List.of (dart:core-patch/array_patch.dart:39:18)
#10     Iterable.toList (dart:core/iterable.dart:498:7)
#11     new ResponseList.fromResultList
responses.dart:34
#12     getPosts
class_detail_provider.dart:44
        <asynchronous suspension>
#13     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure>
base.dart:355
        <asynchronous suspension>
```

What i expected is that, because i explicitly tell that it will be a `RecordModel?` it should be fine to get a null value. Or maybe i did something wrong? Let me know, but once again, thank you so much for your great work!

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the error. Here is a minimal test:

```dart
// example.dart
import "package:pocketbase/pocketbase.dart";

void main() {
  final record = new RecordModel({
    "expand": {"a": RecordModel()}
  });

  final a = record.get<RecordModel?>("test.a");
  final b = record.get<RecordModel?>("test.b");

  print(a is RecordModel);
  print(b == null);
}
```

Running `dart example.dart` (with Dart 3.5.2) doesn't throw an exception and returns `true` in both cases.

If you are still not able to identify the issue please try to provide a minimal reproducible or at least a more complete code sample that can trigger the above error.

**Comment by ganigeorgiev** [comment]
I was able to reproduce it with the following minimal example:

```dart
// example.dart
import "package:pocketbase/pocketbase.dart";

void main() {
  final record = new RecordModel({
    "expand": {"a": {"id": 1}}
  });

  final a = record.get<RecordModel?>("expand.a");
  final b = record.get<RecordModel?>("expand.b");

  print(a is RecordModel);
  print(b == null);
}
```

I'll try to investigate it in more details sometime later today.

**Comment by ganigeorgiev** [comment]
_Side-note: There is another issue similar to this related to `List<T>` castings but I'll push another update for it once I figure out how to properly resolve it._

**Comment by azliR** [comment]
Thank you so much! Really fast response! It fixed, for now it should be enough for me
