### ISSUE TITLE
realtime 'create' event not being received

### ISSUE THREAD

**Issue by agreensh** [pocketbase/dart-sdk#64]
Server:
pocketbase version 0.22.23

Client:
Dart version 3.5.4, Flutter Channel stable 3.24.4
pocketbase: 0.18.1

platforms: iOS, Android, MacOS

I am not receiving the 'create' event for my subscriptions on any collections.
The 'update' and 'delete' events are, however, being received for the same subscriptions.

**Comment by agreensh** [comment]
Yes, it works fine just in standalone dart, but not in a flutter app.

**Comment by ganigeorgiev** [comment]
One thing I forgot to mention is that you may not receive a create event if the subscribed client and the created record don't satisfy the List rule of your collection.

**Comment by agreensh** [comment]
Ok, but I get the event in a Dart program just fine, but not in a Flutter
app so that doesn't explain it

**Comment by agreensh** [comment]
if you do

await pb.create(....);

then

final records = await pb.collection('review').getFullList(
          batch: 200,
          sort: '-updated',
        );

you don't get the create event.

**Comment by agreensh** [comment]
FYI, with an empty List API rule for the collection, it **still** doesn't work.

But, in both cases, if you put a delay before calling _await pb.collection('review').getFullList(_, whether the List API rule is empty or not, it works fine.
So I'll just do that.

**Comment by ganigeorgiev** [comment]
No, sorry this just doesn't make sense.

Either the subscribe call doesn't complete before you are sending the create request or there is something else in your setup that is causing it to fail.

But again, this entire back-and-forth could be avoided if you just create a **minimal** reproducible repo illustrating the problem.
