### ISSUE TITLE
Update realtime docs or realtime function to avoid invalid types

### ISSUE THREAD

**Issue by HadiHassan22** [pocketbase/dart-sdk#65]
The documentation implies the subscribe function takes a listener that listens to events of type RecordSubscriptionEvent. But in reality the subscribe function takes a listener of type SseMessage. 

So even the example in the pub documentation:
```
pb.collection('example').subscribe("*", (e) {
  print(e.action); // create, update, delete
  print(e.record); // the changed record
}, filter: "someField > 10");
```

leads to a linter type error: The getter 'action' isn't defined for the type 'SseMessage'.

I believe either the documentation should be updated to make use of SseMessage type or the function should take a listener of RecordSubscriptionEvent events.

**Comment by ganigeorgiev** [comment]
No you are mistaken, or at least I'm not able to reproduce it (Dart 3.5.2).

[`RecordService.subscribe`](https://pub.dev/documentation/pocketbase/latest/pocketbase/RecordService/subscribe.html) expects the callback to be of [`RecordSubscriptionFunc`](https://pub.dev/documentation/pocketbase/latest/pocketbase/RecordSubscriptionFunc.html) that correctly expect [`RecordSubscriptionEvent`](https://pub.dev/documentation/pocketbase/latest/pocketbase/RecordSubscriptionEvent-class.html).

Feel free to provide a more complete code that could trigger the above linter error but it works correctly for me (you can also test the example in the `example/example.dart`).

**Comment by ganigeorgiev** [comment]
Maybe you are confusing the collection specific subscribe method with the generic `pb.realtime.subscribe`?
