### ISSUE TITLE
"perPage" not respected in response/request

### ISSUE THREAD

**Issue by rodydavis** [pocketbase/dart-sdk#9]
<img width="673" alt="Screen Shot 2022-09-17 at 6 26 26 PM" src="https://user-images.githubusercontent.com/31253215/190881691-84672e17-a2e2-4cc8-a1e4-1a51a2bafc13.png">

**Comment by rodydavis** [comment]
Sent as batch size

**Comment by ganigeorgiev** [comment]
This is working as intented (althought it is not documented very well). We have a server-side `MaxPerPage=200` limit. I'd consider in future versions to increase and document the limit - https://github.com/pocketbase/pocketbase/blob/master/tools/search/provider.go#L16.

**Comment by ganigeorgiev** [comment]
Just to let you know that the `MaxPerPage` limit was raised to 400 in the latest [v0.7.4 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.7.4) (it comes also with huge relations lookup optimizations).

**Comment by rodydavis** [comment]
Perfect, thank you!
